#include "block.h"

SDL_Rect redbrick = {0, 16, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect orangebrick = {31, 0, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect whitebrick = {0, 0, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect bluebrick = {32, 16, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect bluelightbrick ={64,0, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect greenbrick ={98,0,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect navybrick ={128,0,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect darkgreenbrick ={159,0,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect pinkbrick ={64,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect yellowbrick ={96,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect darkredbrick ={128,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect magentabrick ={160,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};

SDL_Rect silverbrick1 = {0, 32, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect silverbrick2= {32, 32, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect silverbrick3= {64, 32, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect silverbrick4= {96, 32, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect silverbrick5= {128, 32, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect silverbrick6= {160, 32, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};

SDL_Rect goldbrick1 = {0, 48, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect goldbrick2= {32, 48, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect goldbrick3= {64, 48, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect goldbrick4= {96, 48, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect goldbrick5= {128, 48, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect goldbrick6= {160, 48, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};

SDL_Rect ball1 = {0, 64, BALL_SPRITE_WIDTH, BALL_SPRITE_HEIGHT};
SDL_Rect ball2 = {16, 64, BALL_SPRITE_WIDTH, BALL_SPRITE_HEIGHT};
SDL_Rect ball3 = {32, 64, BALL_SPRITE_WIDTH, BALL_SPRITE_HEIGHT};
SDL_Rect ball4 = {48, 64, BALL_SPRITE_WIDTH, BALL_SPRITE_HEIGHT};
SDL_Rect ball5 = {64, 64, BALL_SPRITE_WIDTH, BALL_SPRITE_HEIGHT};
SDL_Rect ball6 = {80, 64, BALL_SPRITE_WIDTH, BALL_SPRITE_HEIGHT};

