#include "block.h"

SDL_Rect redbrick = {0, 16, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect orangebrick = {31, 0, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect whitebrick = {0, 0, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect bluebrick = {32, 16, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect bluelightbrick ={64,0, BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect greenbrick ={98,0,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect navybrick ={128,0,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect darkgreenbrick ={159,0,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect pinkbrick ={64,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect yellowbrick ={98,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect darkredbrick ={128,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
SDL_Rect magentabrick ={159,16,BRICK_SPRITE_WIDTH, BRICK_SPRITE_HEIGHT};
