#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "stdbool.h"

#define FPS 120

#define BRICK_SPRITE_WIDTH 30
#define BRICK_SPRITE_HEIGHT 15

#define BRICK_WIDTH BRICK_SPRITE_WIDTH  
#define BRICK_HEIGHT BRICK_SPRITE_HEIGHT 

#define PADDLE_SPRITE_HEIGHT 16

#define BALL_SPRITE_WIDTH 15 
#define BALL_SPRITE_HEIGHT 15

#define BACKGROUND_SPRITE_WIDTH 64
#define BACKGROUND_SPRITE_HEIGHT 64

#define LETTER_SPRITE_WIDTH 32
#define LETTER_SPRITE_HEIGHT 32

#define BOX_WIDTH 32
#define BOX_HEIGHT 32

#define BRICK_ROWS 20
#define BRICK_COLUMNS 40
#define INDIVIDUAL_BRICK_WIDTH 30
#define INDIVIDUAL_BRICK_HEIGHT 15
#define BRICK_PADDING 0

#define MAX_ROWS 13
#define MAX_COLS 16

#define MENU_HEIGHT 90

#define POWERUPS_MAX 64
#define MONSTERS_MAX 32

#define MAX_BOUNCE_ANGLE (120 * M_PI / 180)
#define BALL_SPEED 250.0f

#define MOVE_PROBABILITY 0.5

#define EXPLOSIONS_MAX 16

#endif
