#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "stdbool.h"

#define FPS 60

#define BRICK_SPRITE_WIDTH 30
#define BRICK_SPRITE_HEIGHT 15

#define BRICK_WIDTH BRICK_SPRITE_WIDTH  
#define BRICK_HEIGHT BRICK_SPRITE_HEIGHT 

#define BALL_SPRITE_WIDTH 15 
#define BALL_SPRITE_HEIGHT 15

#define BRICK_ROWS 20
#define BRICK_COLUMNS 40
#define INDIVIDUAL_BRICK_WIDTH 30
#define INDIVIDUAL_BRICK_HEIGHT 15
#define BRICK_PADDING 0

#define MAX_ROWS 20
#define MAX_COLS 40

#endif
